apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mrfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-altinn-gateway_mrfylke_no
      fintlabs.no/org-id: mrfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "mrfylke-no.flyt.*"
        
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "mrfylke-no.altinn.*"
        
      - op: replace
        path: "/spec/orgId"
        value: "mrfylke.no"
        
      - op: add
        path: "/spec/url/basePath"
        value: "/mrfylke-no"
        
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/mrfylke-no/api/altinn"
      
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.org-id"
          value: "mrfylke-no"
          
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.altinn.api.base-url"
          value: "http://fint-altinn-service:8080/"
      
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs"
          value: "INFO"
          
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/mrfylke-no/actuator/health"

    target:
      kind: Application
      name: fint-flyt-altinn-gateway
